title: dale.io
email: dale@dale.io
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dale.io" # the base hostname & protocol for your site
lsi: false
safe: true
twitter_username: obsoke
github_username:  obsoke
highlighter: rouge
permalink: none

# exclude files like gemfile from final build
exclude: ["Gemfile", "Gemfile.lock", "README.md", "CNAME"]
timezone: America/Toronto

# Build settings
markdown: kramdown

old_post_cutoff: 2012-01-23

# plugins
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed

# front matter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: "blog"
      author: "Dale Karp <dale@dale.io>"
